Repository supra1nova/semo-pjt, pull requests merged in 2022-10, with the labels that each got.

#11 swagger 관련 내용 설정
  build.gradle
Labels: enhancement

#13 DTO Class 생성
  src/main/java/com/selfdriven/semo/dto/Booking.java
  src/main/java/com/selfdriven/semo/dto/ImageProduct.java
  src/main/java/com/selfdriven/semo/dto/ImageRoom.java
  src/main/java/com/selfdriven/semo/dto/Product.java
  src/main/java/com/selfdriven/semo/dto/RentInfo.java
  src/main/java/com/selfdriven/semo/dto/Reservation.java
  src/main/java/com/selfdriven/semo/dto/Room.java
Labels: enhancement

#14 sns 로그인 구현
  .gitignore
  build.gradle
  document/semo-erd.mwb
  src/main/java/com/selfdriven/semo/controller/api/KakaoLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/api/MemberApiController.java
  src/main/java/com/selfdriven/semo/controller/api/NaverLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/api/advice/ErrorExceptionHandler.java
  src/main/java/com/selfdriven/semo/controller/view/LoginController.java
  src/main/java/com/selfdriven/semo/controller/view/MainController.java
  src/main/java/com/selfdriven/semo/dto/ApiResponse.java
  src/main/java/com/selfdriven/semo/dto/KakaoAuthResponse.java
  src/main/java/com/selfdriven/semo/dto/KakaoUserInfoResponse.java
  src/main/java/com/selfdriven/semo/dto/Login.java
  src/main/java/com/selfdriven/semo/dto/Member.java
  src/main/java/com/selfdriven/semo/dto/NaverAuthResponse.java
  src/main/java/com/selfdriven/semo/dto/NaverTokenRemoveResponse.java
  src/main/java/com/selfdriven/semo/dto/NaverUserInfoResponse.java
  src/main/java/com/selfdriven/semo/enums/ResultCode.java
  src/main/java/com/selfdriven/semo/mapper/MemberMapper.java
  src/main/java/com/selfdriven/semo/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/static/image/kakao_login_medium_narrow.png
  src/main/resources/template/login.html
  src/main/resources/template/main.html
  src/main/resources/template/naver-callback.html
Labels: documentation, enhancement

#18 sns login 기능 관련 controller, api controller 수정
  build.gradle
  src/main/java/com/selfdriven/semo/controller/api/KakaoLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/api/NaverLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/view/LoginController.java
  src/main/java/com/selfdriven/semo/dto/KakaoAuthResponse.java
  src/main/java/com/selfdriven/semo/dto/Login.java
  src/main/resources/template/join.html
  src/main/resources/template/login.html
  src/main/resources/template/main.html
Labels: enhancement

#19 sns login 관련 오탈자 및 erd 수정
  document/semo.png
  src/main/java/com/selfdriven/semo/controller/api/KakaoLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/api/MemberApiController.java
  src/main/java/com/selfdriven/semo/controller/api/NaverLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/view/LoginController.java
Labels: documentation, enhancement

#21 product CRUD api 개발
  src/main/java/com/selfdriven/semo/controller/ViewController.java
  src/main/java/com/selfdriven/semo/controller/api/ProductApiController.java
  src/main/java/com/selfdriven/semo/dto/ApiResponse.java
  src/main/java/com/selfdriven/semo/dto/Product.java
  src/main/java/com/selfdriven/semo/mapper/ProductMapper.java
  src/main/java/com/selfdriven/semo/service/ProductService.java
  src/main/resources/mapper/ProductMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/META-INF/MANIFEST.MF
Labels: enhancement

#23 sns login 관련 수정
  src/main/java/com/selfdriven/semo/controller/api/KakaoLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/api/MemberApiController.java
  src/main/java/com/selfdriven/semo/controller/api/NaverLoginApiController.java
  src/main/java/com/selfdriven/semo/controller/view/LoginController.java
  src/main/java/com/selfdriven/semo/controller/view/MainController.java
  src/main/java/com/selfdriven/semo/dto/Member.java
  src/main/java/com/selfdriven/semo/dto/login/KakaoAuthResponse.java
  src/main/java/com/selfdriven/semo/dto/login/KakaoUserInfoResponse.java
  src/main/java/com/selfdriven/semo/dto/login/Login.java
  src/main/java/com/selfdriven/semo/dto/login/NaverAuthResponse.java
  src/main/java/com/selfdriven/semo/dto/login/NaverTokenRemoveResponse.java
  src/main/java/com/selfdriven/semo/dto/login/NaverUserInfoResponse.java
  src/main/java/com/selfdriven/semo/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/template/join.html
  src/main/resources/template/main.html
Labels: enhancement

#24 로그인 시퀀스 다이어그램 작성
  document/login-sequence-diagram.png
Labels: documentation

#26 file upload / download 구현
  build.gradle
  src/main/java/com/selfdriven/semo/config/AwsConfig.java
  src/main/java/com/selfdriven/semo/controller/api/S3FileController.java
  src/main/java/com/selfdriven/semo/dto/ImageProduct.java
  src/main/java/com/selfdriven/semo/enums/S3FileEnum.java
  src/main/java/com/selfdriven/semo/mapper/ProductImageMapper.java
  src/main/java/com/selfdriven/semo/service/S3UploadService.java
  src/main/resources/mapper/ProductImageMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/resources/template/main.html
Labels: enhancement

#31 product 특정 업체 수정
  src/main/java/com/selfdriven/semo/controller/api/ProductApiController.java
  src/main/java/com/selfdriven/semo/dto/Product.java
  src/main/java/com/selfdriven/semo/mapper/ProductMapper.java
  src/main/java/com/selfdriven/semo/service/ProductService.java
  src/main/resources/mapper/ProductMapper.xml
Labels: enhancement

#33 S3 이미지 업로드 수정
  src/main/java/com/selfdriven/semo/controller/api/S3FileController.java
  src/main/java/com/selfdriven/semo/service/S3UploadService.java
Labels: enhancement

#36 naver api 관련 ssl handshake 에러 해결 및 db social_type 누락 수정
  src/main/java/com/selfdriven/semo/controller/api/NaverLoginApiController.java
  src/main/resources/mapper/MemberMapper.xml
Labels: enhancement

#38 member, product, room 관련 코드 일부 수정
  src/main/java/com/selfdriven/semo/controller/api/RoomApiController.java
  src/main/java/com/selfdriven/semo/dto/Room.java
  src/main/java/com/selfdriven/semo/mapper/MemberMapper.java
  src/main/java/com/selfdriven/semo/mapper/ProductMapper.java
  src/main/java/com/selfdriven/semo/service/MemberService.java
  src/main/java/com/selfdriven/semo/service/ProductService.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/ProductMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
Labels: enhancement
